{
 "title": "EduProcess - General Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Disponibilidad del Backend",
   "type": "stat",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=~\"eduprocess-backend.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uso de CPU",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 15, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{id=\"/docker\"}[1m])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consumo de RAM por Contenedor",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{id=\"/docker\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tráfico de la API en Tiempo Real",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum(rate(eduprocess_backend_http_requests_total[1m])) by (method, route, status)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}