version: '3.8'

services:
  backend:
    image: xfrixonl/eduprocess-backend:qa
    container_name: eduprocess-backend-qa
    restart: always
    env_file:
      - .env
    networks:
      - eduprocess-qa-network

  frontend:
    image: xfrixonl/eduprocess-frontend:qa
    container_name: eduprocess-frontend-qa
    restart: always
    env_file:
      - .env
    networks:
      - eduprocess-qa-network

  nginx:
    image: nginx:1.25.5-alpine
    container_name: eduprocess-nginx-qa
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - eduprocess-qa-network
    depends_on:
      - backend
      - frontend

networks:
  eduprocess-qa-network:
    driver: bridge